fix #32 - Make every chain parameter conifgurable in yaml
* ensure every cli argument has a yaml equivalent
* --generate-constants takes every cli argument and records it into input yaml, so --create can be passed with zero arguments
* --create still supports arguments, in which case they will override the input yaml (useful for i.e. scale up)

Exception: --cluster parameter is left alone as you could potentially use a different one for create and invite (like a chain created on eks but invited on minikube)

The default values will be filled in `generate-constants`, but create and invite take no default values. To make this work, it was necessary to replace the named arguments with positional argument for the action (create, invite...)

So the new syntax is `mkchain create <chain_name>` instead of `mkchain --create <chain_name>`

Fix README and HOWTO to match the new syntax. Also add a formal parameter list in README.

Remove section of invite code where the zerotier network/token are read from the live configmap since they are now in the chain invite yaml.

Here is now the new help messages look like:

```
[.venv] nochem@peck ~/workspace/tezos-k8s () $ mkchain --help
usage: mkchain [-h] [--cluster CLUSTER] {generate-constants,create,invite} ...

Deploys a private Tezos chain on Kuberenetes

positional arguments:
  {generate-constants,create,invite}
                        See contextual help with mkchain <action> -h
    generate-constants  Generate constants that uniquely define your chain
    create              Create a chain based on constants file
    invite              Generate yaml to invite someone to your chain

optional arguments:
  -h, --help            show this help message and exit
  --cluster CLUSTER     kubernetes cluster type (minikube, eks...)
[.venv] nochem@peck ~/workspace/tezos-k8s () $ mkchain generate-constants --help
usage: mkchain generate-constants [-h] [--number-of-nodes NUMBER_OF_NODES]
                                  [--baker] [--docker-image DOCKER_IMAGE]
                                  [--bootstrap-mutez BOOTSTRAP_MUTEZ]
                                  [--zerotier-network ZEROTIER_NETWORK]
                                  [--zerotier-token ZEROTIER_TOKEN]
                                  [--bootstrap-peer BOOTSTRAP_PEER]
                                  [--genesis-key GENESIS_KEY]
                                  [--genesis-block GENESIS_BLOCK]
                                  [--timestamp TIMESTAMP]
                                  [--protocol-hash PROTOCOL_HASH]
                                  [--baker-command BAKER_COMMAND]
                                  chain_name

Generate constants that uniquely define your chain

positional arguments:
  chain_name            Name of your chain

optional arguments:
  -h, --help            show this help message and exit
  --number-of-nodes NUMBER_OF_NODES
                        number of peers in the cluster
  --baker               Include a baking node in the cluster
  --docker-image DOCKER_IMAGE
                        Version of the Tezos docker image
  --bootstrap-mutez BOOTSTRAP_MUTEZ
                        Initial balance of the bootstrap accounts
  --zerotier-network ZEROTIER_NETWORK
                        Zerotier network id for external chain access
  --zerotier-token ZEROTIER_TOKEN
                        Zerotier token for external chain access
  --bootstrap-peer BOOTSTRAP_PEER
                        peer ip to join
  --genesis-key GENESIS_KEY
                        genesis public key for the chain to join
  --genesis-block GENESIS_BLOCK
                        hash of the genesis block
  --timestamp TIMESTAMP
                        timestamp for the chain to join
  --protocol-hash PROTOCOL_HASH
                        Desired Tezos protocol hash
  --baker-command BAKER_COMMAND
                        The baker command to use, including protocol
```